name: Build and upload assets

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: install dependencies
        run: flutter pub get

      - name: generate runtime code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: build
        run: flutter build apk
      
      - name: rename output APK
        run: |
          mkdir bin
          mv build/app/outputs/flutter-apk/app-release.apk bin/karlsen-mobile-${{ github.event.release.tag_name }}.apk
          
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*.apk
